//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit > Rendering > Generate Shader Includes ] instead
//

#ifndef SHADERCONFIG_HLSL
#define SHADERCONFIG_HLSL
//
// Yarp.YALightingComponent:  static fields
//
#define YALIGHTINGCOMPONENT_EMISSIVE (1)
#define YALIGHTINGCOMPONENT_DIRECT_LIGHT (2)
#define YALIGHTINGCOMPONENT_DIFFUSE_GLOBAL_ILLUMINATION (4)
#define YALIGHTINGCOMPONENT_SPECULAR_REFLECTION (8)

//
// Yarp.YALightLoop:  static fields
//
#define YALIGHTLOOP_SIMPLE (0)

//
// Yarp.ShaderOptions:  static fields
//
#define SHADEROPTIONS_IBL_NORMALIZATION (1)
#define SHADEROPTIONS_IBL_COLOR_ENCODING (1)
#define SHADEROPTIONS_IBL_NUM_OF_MIP_LEVELS_IN_USE (8)
#define SHADEROPTIONS_IBL_ROUGHEST_MIP (1)
#define SHADEROPTIONS_ENVMAP_ROTATION (1)
#define SHADEROPTIONS_CSM_MAX_CASCADES (2)
#define SHADEROPTIONS_MAX_AREA_LIGHTS (4)
#define SHADEROPTIONS_MAX_PUNCTUAL_LIGHTS (16)
#define SHADEROPTIONS_MAX_SHADOWED_LIGHTS (16)
#define SHADEROPTIONS_MAX_SHADOW_SPLITS (64)
#define SHADEROPTIONS_MAX_REFLECTION_PROBES (8)
#define SHADEROPTIONS_LTC_LUT_SIZE (32)
#define SHADEROPTIONS_SPECULAR_OCCLUSION_LUT_SIZE (16)
#define SHADEROPTIONS_COLOR_GRADING_LUT_SIZE (16)
#define SHADEROPTIONS_LIGHT_LOOP_IMPL (0)
#define SHADEROPTIONS_LIGHT_LOOP_TILE_SIZE (16)
#define SHADEROPTIONS_LIGHT_LOOP_MAX_PUNCTUAL_LIGHT_PER_TILE (8)
#define SHADEROPTIONS_LUMA_HISTOGRAM_BINS (256)
#define SHADEROPTIONS_MAX_META_PASS_OUTPUT_VARIABLES (8)
#define SHADEROPTIONS_MAX_META_PASS_RENDER_TARGETS (4)

//
// Yarp.ShaderPass:  static fields
//
#define SHADERPASS_META (1)
#define SHADERPASS_SHADOW_CASTER (2)
#define SHADERPASS_MOTION_VECTORS (4)
#define SHADERPASS_FORWARD_GBUFFER (16)
#define SHADERPASS_FORWARD_BASE (32)

//
// Yarp.ShadowMapFilter:  static fields
//
#define SHADOWMAPFILTER_NONE (0)
#define SHADOWMAPFILTER_FIXED_SIZE_PCF (3)

//
// Yarp.ColorEncoding:  static fields
//
#define COLORENCODING_HDR (0)
#define COLORENCODING_RGBM (1)

//
// Yarp.YALightShape:  static fields
//
#define YALIGHTSHAPE_DIRECTIONAL (1)
#define YALIGHTSHAPE_POINT (2)
#define YALIGHTSHAPE_SPOT (0)


#endif
